In [3]:
import torch
import pandas as pd

### 1. Create Tensor

1-D Tensor

In [4]:
x_list = [1,2,3]
x = torch.tensor(x_list)
print(x)

tensor([1, 2, 3])


attributes of a tensor

In [5]:
#shape
print('tensor shape: ', x.shape)

tensor shape:  torch.Size([3])


In [6]:
#data type
print('tensor data type: ', x.dtype)

tensor data type:  torch.int64


In [7]:
#device for operation
print('tensor operations on device: ', x.device)

tensor operations on device:  cpu


2-D tensor(also called matrix)

In [8]:
x_list = [[1,2,3], [4,5,6]]
x = torch.tensor(x_list)

print('tesor shape: ', x.shape)
print('tensor data type: ', x.dtype)
print('tensor operations on device: ', x.device)

tesor shape:  torch.Size([2, 3])
tensor data type:  torch.int64
tensor operations on device:  cpu


3-D Tensor

In [9]:
x_list = [[[1], [2]], [[3], [4]], [[5], [6]]]
x = torch.tensor(x_list)

In [10]:
print('tensor shape', x.shape)
print('tensor data type: ', x.dtype)
print('tensor operations on device: ', x.device)

tensor shape torch.Size([3, 2, 1])
tensor data type:  torch.int64
tensor operations on device:  cpu


Empty Tensor

In [11]:
x = torch.zeros((6))

print('empty tensor \n', x)

empty tensor 
 tensor([0., 0., 0., 0., 0., 0.])


In [12]:
for i in range(6):
    x[i] = i+1

print('modified tensor \n', x)

modified tensor 
 tensor([1., 2., 3., 4., 5., 6.])


In [13]:
torch.ones((6))

tensor([1., 1., 1., 1., 1., 1.])

#### Creating tensors from Dataset

In [33]:
data_path = "../data/churn_data.csv"

df = pd.read_csv('../../data/churn_data.csv')

column_names = df.columns.values

print('The dataset has {} attributes: \n {}'.format(len(column_names), column_names))


The dataset has 16 attributes: 
 ['year' 'customer_id' 'phone_no' 'gender' 'age' 'no_of_days_subscribed'
 'multi_screen' 'mail_subscribed' 'weekly_mins_watched'
 'minimum_daily_mins' 'maximum_daily_mins' 'weekly_max_night_mins'
 'videos_watched' 'maximum_days_inactive' 'customer_support_calls' 'churn']


In [34]:
df.head()

year  customer_id  phone_no  gender  age  no_of_days_subscribed  \
0  2015       100198  409-8743  Female   36                     62   
1  2015       100643  340-5930  Female   39                    149   
2  2015       100756  372-3750  Female   65                    126   
3  2015       101595  331-4902  Female   24                    131   
4  2015       101653  351-8398  Female   40                    191   

  multi_screen mail_subscribed  weekly_mins_watched  minimum_daily_mins  \
0           no              no               148.35                12.2   
1           no              no               294.45                 7.7   
2           no              no                87.30                11.9   
3           no             yes               321.30                 9.5   
4           no              no               243.00                10.9   

   maximum_daily_mins  weekly_max_night_mins  videos_watched  \
0               16.81                     82               1   
1               33.37                     87               3   
2                9.89                     91               1   
3               36.41                    102               4   
4               27.54                     83               7   

   maximum_days_inactive  customer_support_calls  churn  
0                    4.0                       1    0.0  
1                    3.0                       2    0.0  
2                    4.0                       5    1.0  
3                    3.0                       3    0.0  
4                    3.0                       1    0.0

In [35]:
x = torch.tensor(df[['weekly_mins_watched', 'minimum_daily_mins', 'maximum_daily_mins']].values)

In [36]:
x.shape

torch.Size([2000, 3])

In [37]:
x.dtype

torch.float64

In [39]:
x2 = torch.add(x,x)

print(x2)
print('x2 shape: {}', x2.shape)

tensor([[296.7000,  24.4000,  33.6200],
        [588.9000,  15.4000,  66.7400],
        [174.6000,  23.8000,  19.7800],
        ...,
        [257.7000,  31.2000,  29.2000],
        [356.1000,  20.8000,  40.3600],
        [653.4000,  20.6000,  74.0600]], dtype=torch.float64)
x2 shape: {} torch.Size([2000, 3])


In [41]:
x3 = torch.sub(x,x)

print(x3)
print('x3 shape: {}', x3.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
x3 shape: {} torch.Size([2000, 3])


In [42]:
x4 = torch.multiply(x,x)

print(x4)
print('x4 shape: {}', x4.shape)

tensor([[2.2008e+04, 1.4884e+02, 2.8258e+02],
        [8.6701e+04, 5.9290e+01, 1.1136e+03],
        [7.6213e+03, 1.4161e+02, 9.7812e+01],
        ...,
        [1.6602e+04, 2.4336e+02, 2.1316e+02],
        [3.1702e+04, 1.0816e+02, 4.0723e+02],
        [1.0673e+05, 1.0609e+02, 1.3712e+03]], dtype=torch.float64)
x4 shape: {} torch.Size([2000, 3])


In [44]:
x5 = x @ x.T

print(x5)
print('x5 shape: {}', x5.shape)

tensor([[ 22439.1386,  44336.5472,  13262.3859,  ...,  19550.6435,
          26879.8233,  49214.0793],
        [ 44336.5472,  87873.6494,  26127.1443,  ...,  38547.2045,
          53180.3091,  97511.8161],
        [ 13262.3859,  26127.1443,   7860.7121,  ...,  11578.6390,
          15867.1052,  29009.7067],
        ...,
        [ 19550.6435,  38547.2045,  11578.6390,  ...,  17058.8425,
          23398.6105,  42796.6130],
        [ 26879.8233,  53180.3091,  15867.1052,  ...,  23398.6105,
          32217.1949,  59023.3204],
        [ 49214.0793,  97511.8161,  29009.7067,  ...,  42796.6130,
          59023.3204, 108210.2009]], dtype=torch.float64)
x5 shape: {} torch.Size([2000, 2000])
